import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	copyAssets();
	process.exit(0);
} else {
	await context.watch();
	copyAssets();
}

function copyAssets() {
	if (!fs.existsSync("dist")) {
		fs.mkdirSync("dist");
	}
	// Sync manifest and styles to dist
	fs.copyFileSync("manifest.json", path.join("dist", "manifest.json"));
	if (fs.existsSync("styles.css")) {
		fs.copyFileSync("styles.css", path.join("dist", "styles.css"));
	}

	// Also ensure main.js is available at the root for Obsidian's development mode
	if (fs.existsSync("dist/main.js")) {
		fs.copyFileSync("dist/main.js", "main.js");
	}
}
